### ISSUE TITLE
Tests do not run

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/domite#8]
I did

### Setup 

     mkdir amberdomite
     cd amberdomite/
     amber init
     bower install domite --save
     amber serve

### SUnit test

Open ``localhost:4000`` in web browser.

Run SUnit test

### Problem

The tests do not run properly, see screen shots.

![amber-domite-sunit-2015-02-22_05 31 20](https://cloud.githubusercontent.com/assets/1112023/6317596/c8a8182c-ba54-11e4-9d72-c5189dcdd681.png)

![amber-domite_test_first_ide_2015-02-22 05 33 00](https://cloud.githubusercontent.com/assets/1112023/6317597/cd286e1a-ba54-11e4-93fa-9aa7f12094c4.png)

**Comment by hhzl** [comment]
This is on FF34 on Linux Mint

**Comment by herby** [comment]
There's nothing wrong on this. Each new project has 0 tests.

**Comment by hhzl** [comment]
But I understood that you have added test cases, why do they not run?

**Comment by herby** [comment]
You created new project. You are not developing Domite. What makes you think they should run when they are not included at all?

Hannes Hirzel wrote:
> But I understood that you have added test cases, why do they not run?
>

**Comment by hhzl** [comment]
OK, thanks....

**Comment by herby** [comment]
It's up on you what you put in `devel.js`.

Hannes Hirzel wrote:

**Comment by hhzl** [comment]
Yes.

**Comment by hhzl** [comment]
Fork repo

      git clone https://github.com/hhzl/domite.git
      cd domite
      npm install
      bower install
      grunt devel
      amber serve

![amber-domite-sunit_2015-02-22 15 17 02](https://cloud.githubusercontent.com/assets/1112023/6319036/32f4c080-baa6-11e4-840d-c1381938bbbe.png)
